server:
  port: 8090
  
api:
  coingecko:
    domain: "api.coingecko.com"
    endpoints:
      coin_market_usd: "/api/v3/coins/markets"
    parameters:
      vs_currency: "usd"
      x_cg_demo_api_key: "CG-cTyrK8iCq46x38hgMQZfgGGQ"


spring.datasource:
  driverClassName: "org.hibernate.dialect.PostgreSQLDialect" 
  url: "jdbc:postgresql://localhost:5432/${database.postgres}"
  username: "postgres"
  password: "admin1234"

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update # update
  
  # Hibernate ddl auto (create, create-drop, validate, update)
# https://
# api.coingecko.com
# /api/v3/coins/markets -> split("/")
# vs_currency=usd
# x_cg_demo_api_key=CG-cTyrK8iCq46x38hgMQZfgGGQ