server:
  port: 8092

api:
  internal:
    crypto:
      host: "localhost"
      port: 8090
      basepath: "/crypto/coingecko/api/v1"
      endpoints:
        markets: "/coins/markets"
        list: "/coins/list"
    stock:
      host: "localhost"
      port: 8091
      basepath: "/stock/finnhub/api/v1"
      endpoints:
        quote: "/quote"
        profile2: "/profile2"
        symbols: "/symbols"

database:
  postgres: "db_quote"

spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/${database.postgres}"
    username: "postgres"
    password: "Bibuchu#1"
  jpa:
    show-sql: true
    hibernate.ddl-auto: update